import React from 'react'
import Head from 'next/head'

export const Proposta = (): JSX.Element => {

  return (
    <div>
      <Head>
        <title>Setup Next JS.</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>
          Setup Next JS.
        </h1>
      </main>
    </div>
  )
}

export default Proposta
